/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package parser;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTMAIN_FUN = 1;
  public int JJTFUNSATEMENT = 2;
  public int JJTTYPE = 3;
  public int JJTDECLEARSTATEMENT = 4;
  public int JJTASSIGNSTATEMENT = 5;
  public int JJTOREXPRESSION = 6;
  public int JJTANDEXPRESSION = 7;
  public int JJTNOBOOLEXPRESSION = 8;
  public int JJTRELEXPRESSION = 9;
  public int JJTIFSTATEMENT = 10;
  public int JJTAUTOADD = 11;
  public int JJTWHILESTATEMENT = 12;
  public int JJTFORSTATEMENT = 13;
  public int JJTDOWHILESTATEMENT = 14;
  public int JJTSWITCHSTATEMENT = 15;
  public int JJTSTATEMENT = 16;
  public int JJTSTATEMENTBLOCK = 17;
  public int JJTEXPRESSION = 18;
  public int JJTADDITIVEEXPRESSION = 19;
  public int JJTMULTIPLICATIVEEXPRESSION = 20;
  public int JJTUNARYEXPRESSION = 21;
  public int JJTIDENTIFIER = 22;
  public int JJTINTEGER = 23;


  public String[] jjtNodeName = {
    "Start",
    "main_fun",
    "funSatement",
    "Type",
    "declearStatement",
    "assignStatement",
    "orExpression",
    "andExpression",
    "NoBOOLExpression",
    "relExpression",
    "ifStatement",
    "AutoAdd",
    "whileStatement",
    "forStatement",
    "doWhileStatement",
    "SwitchStatement",
    "statement",
    "statementBlock",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=315bd43e92d60c704b27b977e59af6b8 (do not edit this line) */
